### ISSUE TITLE
retrying the request, and canceling the current one if it's in progress.

### ISSUE THREAD

**Issue by sorahn** [dai-shi/react-hooks-fetch#2]
I have a class component that allows you to click a 'retry' button, and when you do that it also aborts the existing request.  Would that work with this hook? 

I was just about to sit down and puzzle together a hook for this, and when googling I came across your [blog post](https://itnext.io/usefetch-react-custom-hook-for-fetch-api-with-suspense-and-concurrent-mode-in-mind-1d3ba9250e0).

Here's what my component looks like currently: https://gist.github.com/sorahn/bb244c2569c8a2614cc49a180b4b3f37

**Comment by dai-shi** [comment]
This library is still experimental with Suspense. (The [old version](https://github.com/dai-shi/react-hooks-fetch/tree/767cba39180c88be2960061028004e32aaea6e4b) without Suspense might work.)

I'd recommend trying out my other library [react-hooks-async](https://github.com/dai-shi/react-hooks-async) which should be relatively stable and is more controllable.
The repo has [several examples](https://github.com/dai-shi/react-hooks-async#examples) and there are [some blog posts](https://github.com/dai-shi/react-hooks-async#blogs) too.
I think it would cover most of your use cases. (I haven't tried abort timeout, though.)

**Comment by sorahn** [comment]
Ah, yeah for something like suspense, I guess the retry mechanic wouldn't make sense really.

react-hooks-async looks great.  Thanks!
