### ISSUE TITLE
what if two components make requests to the same URL?

### ISSUE THREAD

**Issue by NullVoxPopuli** [dai-shi/react-hooks-fetch#3]
like, if I want to use `useFetch` in a HoC, and that HoC gets used in a few places -- at present, fetch will be invoked once per usage

**Comment by dai-shi** [comment]
As you might guess, this hook simply invokes `fetch` and it doesn't have any caching mechanism by itself. It's up to browser how it's handled. The server may respond with different contents for the same URL (imagine a counter page). Browser could cache the content with proper response headers, but I'm not sure and I didn't experiment on it.

What do you think, and what is your expectation?

**Comment by dai-shi** [comment]
I did a bit of experiment in Chrome.

<img width="698" alt="json api" src="https://user-images.githubusercontent.com/490574/52521492-33bc5d80-2cbb-11e9-8b81-88ea6601dbdd.png">
This is JSON API. It seems waiting the first one to finish and then send the same request.

----

<img width="735" alt="static file" src="https://user-images.githubusercontent.com/490574/52521499-53538600-2cbb-11e9-894f-7d7cd48343fc.png">
This is a static file. The second one is finished at the same time and the size is `0 B`.

**Comment by dai-shi** [comment]
Closing this one. Feel free to reopen for further discussion.
