### ISSUE TITLE
Support fetching an array of requests.

### ISSUE THREAD

**Issue by BruceL33t** [dai-shi/react-hooks-fetch#5]
What if I have a component that needs to do multiple fetch requests? Eg. a chart with an endpoint for each series? How would you extend this hook to be able to handle multiple fetch requests? And preferably a way to return data whenever a promise resolves, instead of Promise.all.

**Comment by dai-shi** [comment]
Hi,

> How would you extend this hook to be able to handle multiple fetch requests?

Literally, we need to extend it to accept an array.
(I really want react-cache to come for such a complex scenario.)

> preferably a way to return data whenever a promise resolves

You might want to check my another project.
https://github.com/dai-shi/react-hooks-async
It should be a bit easier to extend for that.
If the number of requests is fixed, it can be done like [this example](https://github.com/dai-shi/react-hooks-async/tree/master/examples/06_progress).

**Comment by dai-shi** [comment]
I have another idea...

```javascript
const FetchOne = ({ url, setData }) => {
  const { data } = useFetch(url);
  const prev = usePrevious(data);
  if (data && prev !== data) {
    setData(data);
  }
  return null;
};

const FetchAll = ({ urls }) => {
  const [result, setResult] = useState([]);
  const updateResult = (index, data) => {
    const copy = [...result];
    copy[index] = data;
    setResult(copy);
  };
  return (
    <React.Fragment>
      {urls.map((url, index) => <FetchOne url={url} setData={data => updateResult(index, data)} />}
      <ShowResult result={result} />
    </React.Fragment>
  );
};
```

**Comment by BruceL33t** [comment]
Thanks @dai-shi - I will try your suggestions and see if I can get it working.
