### ISSUE TITLE
Passing options

### ISSUE THREAD

**Issue by tyleratredspace** [dai-shi/react-hooks-fetch#6]
Passing options such as headers to useFetch will never resolve a response (no error either).
The network request is still made and finishes, but the response does not resolve in the app.

**WORKS:** 
`const { error, data } = useFetch(url);`
When logging out the useFetch arguments a successful request looks like this.
![image](https://user-images.githubusercontent.com/27648624/55484669-4ee28400-55ff-11e9-9798-3dce9e2eda32.png)

**FAILS:** 
```
const { error, data } = useFetch(url, {
  headers: {
    // SOME HEADERS HERE
  }
});
```

**ALSO FAILS:** 
```
const { error, data } = useFetch(url, {}); // This is strange as defaultOpts are also {}
```
When logging out the useFetch arguments a failed request looks like this.
![image](https://user-images.githubusercontent.com/27648624/55484775-7e918c00-55ff-11e9-84b2-6151b7281227.png)

**Comment by dai-shi** [comment]
This is tricky part of render. Either define opts outside of render, or useMemo.

I should clearly note it somewhere...

**Comment by tyleratredspace** [comment]
Wow, that works!  You just saved me so much time!

**Comment by dai-shi** [comment]
One note just in case: This is an experimental library to try Fetch and Suspense. If you need more stable one without Suspense, I recommend another library of mine: https://github.com/dai-shi/react-hooks-async which has similar `useFetch`.

**Comment by zerdos** [comment]
I also spent 3-4 hours of debugging before I found this thread. 
It should give you an error message with an explanation when the render fails because of this reason.

**Comment by dai-shi** [comment]
Good point. If it's invoked several times in a short period, we could show a message, only in DEV mode.

Only a hesitation I have is that I can tell what's happening but not a solution. I'm still looking for a best practice how to deal with it. I tried a naive useMemoPrev in examples/02_extended because useMemo could forget a memoized value.

**Comment by dai-shi** [comment]
I misunderstood something. It's far more complicated. e02a68d460ff31186302a24ac802b839f91058ae shows the message but it's really a dirty hack.

Please use https://github.com/dai-shi/react-hooks-async unless you need to do some experiments on Suspense.

**Comment by dai-shi** [comment]
See: https://github.com/dai-shi/react-hooks-fetch/blob/1f420deb7515932b6cb469fcfc75c4dbc9e627a0/examples/02_extended/src/index.js#L6

This uses useMemoOne to provide semantic guarantee.
https://github.com/alexreardon/use-memo-one
